// Generated by tsbindgen - Architecture
// Namespace: express
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './index/internal/index.js';

// Cross-namespace type imports for constraints
import type { Dictionary, IEnumerable, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { Action, AsyncCallback, Boolean as ClrBoolean, Byte, DateTime, Exception, IAsyncResult, ICloneable, Int32, Int64, IntPtr, MulticastDelegate, Nullable, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { ISerializable } from '@tsonic/dotnet/System.Runtime.Serialization.js';
import type { Task } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { Application as Application } from './index/internal/index.js';
export { AppServer as AppServer } from './index/internal/index.js';
export type NextFunction = Internal.NextFunction;
export type RequestHandler = Internal.RequestHandler;
export type ErrorRequestHandler = Internal.ErrorRequestHandler;
export type ParamHandler = Internal.ParamHandler;
export type VerifyBodyHandler = Internal.VerifyBodyHandler;
export type MediaTypeMatcher = Internal.MediaTypeMatcher;
export type CookieEncoder = Internal.CookieEncoder;
export type QueryParser = Internal.QueryParser;
export type TrustProxyEvaluator = Internal.TrustProxyEvaluator;
export type TemplateEngine = Internal.TemplateEngine;
export type SetHeadersHandler = Internal.SetHeadersHandler;
export { RouterOptions as RouterOptions } from './index/internal/index.js';
export { JsonOptions as JsonOptions } from './index/internal/index.js';
export { RawOptions as RawOptions } from './index/internal/index.js';
export { TextOptions as TextOptions } from './index/internal/index.js';
export { UrlEncodedOptions as UrlEncodedOptions } from './index/internal/index.js';
export { MultipartField as MultipartField } from './index/internal/index.js';
export { MultipartOptions as MultipartOptions } from './index/internal/index.js';
export { CorsOptions as CorsOptions } from './index/internal/index.js';
export { StaticOptions as StaticOptions } from './index/internal/index.js';
export { SendFileOptions as SendFileOptions } from './index/internal/index.js';
export { DownloadOptions as DownloadOptions } from './index/internal/index.js';
export { CookieOptions as CookieOptions } from './index/internal/index.js';
export { RangeOptions as RangeOptions } from './index/internal/index.js';
export { ByteRange as ByteRange } from './index/internal/index.js';
export { RangeResult as RangeResult } from './index/internal/index.js';
export { FileStat as FileStat } from './index/internal/index.js';
export { express$instance as express } from './index/internal/index.js';
export { Multipart as Multipart } from './index/internal/index.js';
export { Cookies as Cookies } from './index/internal/index.js';
export { Files as Files } from './index/internal/index.js';
export { Params as Params } from './index/internal/index.js';
export { Request as Request } from './index/internal/index.js';
export { UploadedFile as UploadedFile } from './index/internal/index.js';
export { Response as Response } from './index/internal/index.js';
export { Route as Route } from './index/internal/index.js';
export { Router as Router } from './index/internal/index.js';
export { RoutingHost_1 as RoutingHost } from './index/internal/index.js';
